// typescript-react/Human.tsx
import React, { FC } from "react";

const Children: FC = ({ children }) => <div>{children}</div>;

const Id = Children;
const Name = Children;
const Age = Children;
const Description = Children;

export const Human: FC = () => (
  <>
    <Id>@human</Id>
    <Name>human</Name>
    <Age>17</Age>
    <Description>New Human</Description>
  </>
);

// javascript-vue/Human.vue
<template>
  <div>
    <div>{{id}}</div>
    <div>{{name}}</div>
    <div>{{age}}</div>
    <div>{{description}}</div>
  </div>
</template>

<script>
export default {
  name: "Human",
  data() {
    return {
      id: "@human",
      name: "human",
      age: 17,
      description: "New Human"
    };
  }
};
</script>
